### ISSUE TITLE
Broken dependency on powershell 

### ISSUE THREAD

**Issue by s0lucien** [gildas/puppet-sqlserver#3]
I am unable to install this due to the wrong powershell dependency 
 {"name": "puppetlabs/powershell", "version_requirement": ">=3.0.0 <5.0.0"},

As far as i can see, puppetlabs-powershell is only 2.0.2 as of today

https://forge.puppet.com/puppetlabs/powershell

This leads to librarian-puppet giving me 
[Librarian] Conflict between puppetlabs-powershell (< 3.0.0, >= 1.0.1) https://forgeapi.puppetlabs.com and puppetlabs-powershell (< 5.0.0, >= 3.0.0) https://forgeapi.puppetlabs.com

**Comment by gildas** [comment]
Weird it has been working until now.
On it.

**Comment by gildas** [comment]
Oh, and sorry for the late reply, I was on vacation <blush/>

**Comment by s0lucien** [comment]
I fixed it in a fork , should i submit a PR ?

**Comment by gildas** [comment]
The code is already written in the master branch.

I changed the deps to this:

``` json
  "dependencies": [
    {"name": "puppetlabs/stdlib",     "version_requirement": ">=2.7.0 <6.0.0"},
    {"name": "puppetlabs/powershell", "version_requirement": ">=2.0.0 <6.0.0"},
    {"name": "gildas/firewall",       "version_requirement": ">=0.1.0 <1.0.0"}
  ]
```

Now, are you able to test this code without me publishing the module?

**Comment by gildas** [comment]
It's kind of late here (over midnight) and that test would help me.

**Comment by s0lucien** [comment]
i am testing it right now

**Comment by gildas** [comment]
cool thanks!

**Comment by s0lucien** [comment]
resolving it worked, thanks !

**Comment by gildas** [comment]
Great! Thanks a lot.
I am going to publish the module on puppetlabs.

**Comment by gildas** [comment]
ok, module updated on the forge.

https://forge.puppet.com/gildas/sqlserver
